name: SurvivalGames
version: 0.7.5
main: com.thundergemios10.survivalgames.SurvivalGames
## Authors ##
authors: [Double0Negative, ThunderGemios10, remyboy2003]
description: Fully Automated Hunger Games Plugin!
depend: [WorldEdit]

commands:
    survivalgames:
        description: Survival Games Command
        usage: /sg <command> <args>
        aliases: [sg, hungergames, hg]
        
